protagonists = [
    {"Protagonist": "Arthur Fleck (Joker)", "Original Story": "Joker", "Author": "Todd Phillips and Scott Silver"},
    {"Protagonist": "Beatrix Kiddo (The Bride)", "Original Story": "Kill Bill series", "Author": "Quentin Tarantino"},
    {"Protagonist": "Bilbo Baggins", "Original Story": "The Hobbit", "Author": "J.R.R. Tolkien"},
    {"Protagonist": "Bruce Wayne", "Original Story": "Batman", "Author": "Bob Kane and Bill Finger"},
    {"Protagonist": "Clark Kent", "Original Story": "Superman", "Author": "Jerry Siegel and Joe Shuster"},
    {"Protagonist": "Commander Shepard", "Original Story": "Mass Effect series", "Author": "Drew Karpyshyn"},
    {"Protagonist": "Don Draper", "Original Story": "Mad Men", "Author": "Matthew Weiner"},
    {"Protagonist": "Ellen Ripley", "Original Story": "Alien series", "Author": "Dan O'Bannon and Ronald Shusett"},
    {"Protagonist": "Ezio Auditore", "Original Story": "Assassin's Creed series", "Author": "Corey May"},
    {"Protagonist": "Frank Castle (The Punisher)", "Original Story": "The Punisher", "Author": "Gerry Conway, John Romita Sr., and Ross Andru"},
    {"Protagonist": "Frank Underwood", "Original Story": "House of Cards", "Author": "Michael Dobbs (original novel), Beau Willimon (US adaptation)"},
    {"Protagonist": "Frodo Baggins", "Original Story": "The Lord of the Rings", "Author": "J.R.R. Tolkien"},
    {"Protagonist": "Gandalf", "Original Story": "The Lord of the Rings", "Author": "J.R.R. Tolkien"},
    {"Protagonist": "Geralt of Rivia", "Original Story": "The Witcher series", "Author": "Andrzej Sapkowski"},
    {"Protagonist": "Gollum", "Original Story": "The Lord of the Rings", "Author": "J.R.R. Tolkien"},
    {"Protagonist": "Hercules", "Original Story": "Greek Mythology", "Author": "Various Ancient Greek authors"},
    {"Protagonist": "Hermione Granger", "Original Story": "Harry Potter series", "Author": "J.K. Rowling"},
    {"Protagonist": "Indiana Jones", "Original Story": "Indiana Jones series", "Author": "George Lucas"},
    {"Protagonist": "Jack Torrance", "Original Story": "The Shining", "Author": "Stephen King"},
    {"Protagonist": "James Bond", "Original Story": "James Bond series", "Author": "Ian Fleming"},
    {"Protagonist": "John Constantine", "Original Story": "Hellblazer/Constantine", "Author": "Alan Moore, Stephen R. Bissette, and John Totleben"},
    {"Protagonist": "John Wick", "Original Story": "John Wick series", "Author": "Derek Kolstad"},
    {"Protagonist": "Jon Snow", "Original Story": "Game of Thrones", "Author": "George R.R. Martin"},
    {"Protagonist": "Jules Winnfield", "Original Story": "Pulp Fiction", "Author": "Quentin Tarantino"},
    {"Protagonist": "Katniss Everdeen", "Original Story": "The Hunger Games", "Author": "Suzanne Collins"},
    {"Protagonist": "King Arthur", "Original Story": "Arthurian Legends", "Author": "Various Medieval authors"},
    {"Protagonist": "Kratos", "Original Story": "God of War series", "Author": "David Jaffe"},
    {"Protagonist": "Lara Croft", "Original Story": "Tomb Raider series", "Author": "Toby Gard"},
    {"Protagonist": "Lisbeth Salander", "Original Story": "The Girl with the Dragon Tattoo", "Author": "Stieg Larsson"},
    {"Protagonist": "Logan (Wolverine)", "Original Story": "X-Men", "Author": "Len Wein and John Romita Sr."},
    {"Protagonist": "Lou Bloom", "Original Story": "Nightcrawler", "Author": "Dan Gilroy"},
    {"Protagonist": "Luke Skywalker", "Original Story": "Star Wars", "Author": "George Lucas"},
    {"Protagonist": "Mad Max", "Original Story": "Mad Max series", "Author": "George Miller and Byron Kennedy"},
    {"Protagonist": "Marv", "Original Story": "Sin City", "Author": "Frank Miller"},
    {"Protagonist": "Master Chief", "Original Story": "Halo series", "Author": "Joseph Staten"},
    {"Protagonist": "Michael Corleone", "Original Story": "The Godfather series", "Author": "Mario Puzo"},
    {"Protagonist": "Nathan Drake", "Original Story": "Uncharted series", "Author": "Amy Hennig"},
    {"Protagonist": "Neo", "Original Story": "The Matrix series", "Author": "The Wachowskis"},
    {"Protagonist": "Odysseus", "Original Story": "The Odyssey", "Author": "Homer"},
    {"Protagonist": "Omar Little", "Original Story": "The Wire", "Author": "David Simon"},
    {"Protagonist": "Patrick Bateman", "Original Story": "American Psycho", "Author": "Bret Easton Ellis"},
    {"Protagonist": "Paul Atreides", "Original Story": "Dune series", "Author": "Frank Herbert"},
    {"Protagonist": "Peter Parker", "Original Story": "Spider-Man", "Author": "Stan Lee and Steve Ditko"},
    {"Protagonist": "Raoul Duke", "Original Story": "Fear and Loathing in Las Vegas", "Author": "Hunter S. Thompson"},
    {"Protagonist": "Rorschach", "Original Story": "Watchmen", "Author": "Alan Moore and Dave Gibbons"},
    {"Protagonist": "Samus Aran", "Original Story": "Metroid series", "Author": "Makoto Kano"},
    {"Protagonist": "Sephiroth", "Original Story": "Final Fantasy VII", "Author": "Yoshinori Kitase and Kazushige Nojima"},
    {"Protagonist": "Sherlock Holmes", "Original Story": "Sherlock Holmes stories", "Author": "Arthur Conan Doyle"},
    {"Protagonist": "Solid Snake", "Original Story": "Metal Gear series", "Author": "Hideo Kojima"},
    {"Protagonist": "Thomas Shelby", "Original Story": "Peaky Blinders", "Author": "Steven Knight"},
    {"Protagonist": "Tony Montana", "Original Story": "Scarface", "Author": "Oliver Stone"},
    {"Protagonist": "Tony Stark", "Original Story": "Iron Man", "Author": "Stan Lee, Larry Lieber, Don Heck, and Jack Kirby"},
    {"Protagonist": "Travis Bickle", "Original Story": "Taxi Driver", "Author": "Paul Schrader"},
    {"Protagonist": "Tyler Durden", "Original Story": "Fight Club", "Author": "Chuck Palahniuk"},
    {"Protagonist": "Venom (Eddie Brock)", "Original Story": "Spider-Man", "Author": "David Michelinie and Todd McFarlane"},
    {"Protagonist": "Vincent Vega", "Original Story": "Pulp Fiction", "Author": "Quentin Tarantino"},
    {"Protagonist": "Vito Corleone", "Original Story": "The Godfather series", "Author": "Mario Puzo"},
    {"Protagonist": "Walter White", "Original Story": "Breaking Bad", "Author": "Vince Gilligan"}
]